name: closetalk
description: "Connect with people around you, without a network connection"
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^9.1.2
  flutter_nearby_connections: ^1.1.2
  get: ^4.6.6
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  path_provider: ^2.1.2
dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.3.10
  flutter_launcher_icons: ^0.13.1
  isar_generator: ^3.1.0
  build_runner: ^2.4.8
flutter:
  uses-material-design: true
