name: closetalk
description: "Connect with people around you, without a network connection"
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  device_info_plus: ^9.1.2
  flutter:
    sdk: flutter
  flutter_nearby_connections: ^1.1.2
  get: ^4.6.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  marquee: ^2.2.3
  path_provider: ^2.1.2

dev_dependencies:
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.3.10
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
