name: closetalk
description: "Connect with people around you, without a network connection"
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  awesome_notifications: ^0.9.2
  awesome_notifications_core: ^0.9.1
  device_info_plus: ^9.1.2
  easy_animate: ^0.0.3
  flutter:
    sdk: flutter
  flutter_nearby_connections: ^1.1.2
  flutter_scatter: ^0.2.0
  get: ^4.6.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  marquee: ^2.2.3
  path_provider: ^2.1.2
  random_avatar: ^0.0.8

dev_dependencies:
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/icon.png
    - assets/OpenSans.ttf
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/OpenSans.ttf

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false
